### ISSUE TITLE
How to narrow the response type

### ISSUE THREAD

**Issue by jgoux** [paambaati/neon-js-sdk#11]
Hello, and thanks for publishing this typed Neon client!

I'm trying to create a project using `neonClient.project.createProject` but I notice that I don't have proper types for the response:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1443499/234328380-e1daa661-d60a-41e9-b873-727a35ed406d.png">

The fact that the response is a union of `GeneralError` and the "success" type makes it impossible to properly have the response typed:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1443499/234328901-ffc83a41-1f53-4673-988e-d507ef0e5abb.png">

To have something usable, I did:

```ts
type FixNeonClient<T extends NeonClient> = {
  [K in keyof T]: {
    [K2 in keyof T[K]]: T[K][K2] extends (
      ...args: infer TArgs
    ) => Promise<infer TReturn>
      ? (...args: TArgs) => Promise<Exclude<TReturn, GeneralError>>
      : T[K][K2]
  }
}

export const neonClient = new NeonClient({
  TOKEN: processEnv.NEON_API_KEY,
}) as unknown as FixNeonClient<NeonClient>
```

but that's definitely a hack. 😅 

Thanks for your help. 🙇‍♂️

**Comment by paambaati** [comment]
@jgoux Thanks for raising this.

Your solution kinda works. Here's another way to do it, case-by-case – https://www.typescriptlang.org/play?isolatedModules=true&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzgOQKYQHYGEA2xUbwC+cAZlBCHAOQboYC0AzgCYDW1A3AFCiSxwYATzCpEcAOIFUUAIY4AolApQ4JcpRp1Mzdl27cAxpibxt2PAXgBeOHQDuKernyEAFAm5xvcACoB5AGkFZAAuGgAeAElkAGUFACVfFAV-ZDgAQQAFKLhggE04AAlEhQA+agAabiIASh5uYVE4LChUWRhULIoAK1RDGCUVADE21ATUJkgMJjFbbspgWYiFAA9DHABXFlQIjPtZYE6WCImYTagMXxFdpvRSO2dLQgA6MF7+mBfDNo6uj4GZTKlUk0jkimU0CBRhM8B+7U6Cz6AwmUxMc0emBcVjeAK+8L+SM+Hi8PneEGRMHCnh8tLsshAqHC1FkACNDFVSXS4G0AObATAAfWALGZ9mgOBYnO53jAvMFADcZEwBRhwgBGAAs1VpRBqtTgsiYLV+iLxQ2go1Q40m01mBgJZopn1RdtQ3CAA

All said, the types are defined that way because the response _could_ technically be a `GeneralError`. A much better way to handle this is explicitly using a type-guard so that you can handle the error however you see fit – https://www.typescriptlang.org/play?isolatedModules=true&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzgOQKYQHYGEA2xUbwC+cAZlBCHAOQboYC0AzgCYDW1A3AFCiSxwYATzCpEcLAEMMAY1Q5JAIxyoAChRDAmqADRwA4gVRRJOAKJQKUOCXKUadTM3Zdu3GZibxH2PAXgAvHB0AO4o9Lj4hAAUCNxwCXAAKgDyANJmyABcNAA8AJLIAMpmAEpJKGYpyHAAgqr5cBkAmnAAEmVmAHzUOtxEAJQ83AD0AFRj8WPJIqgMAOYArpJQLIIAFpLwMPI4THBCEItwwKQbYvPAAG4EcBCKAFaoMvBacJJwAAaGdCbmltBPmQNOFMAA6KYjbikRayGDATAnJhoTAWKzRHylVBMSAYbQ5aRCAY5THY3HaJEGIx-NHQRDxRKnODRYSiCBnUk4zyoMEwda3AKCmgwuEIjDUAb0xLSuBQVAwRZQDDBehYrl4nl8gjRaJy9X494YIlwAJdKUyi1M3Vk7lgjwsMQAMkdglm7NlNo1YJA2KYknmYkFQWoXigwAw8wl5ot0rlCqVgigi1QPBjMqIDLTCTjiuVpFM2lTMcGRYSGdj8tzZALKf6bg8ePgMjlWzUFCeLzV5MD7xCkmA3gifkIYLA7eeMDtLZ26ggHZgsUzcDHc4nOTiaYwkh9OWoShkvSXFcumAA+sAWLuQtAcCxD2mwPNTzcoEwxTkAIwAFj60ozJbcK0tBRDBaSgaJm1QVtZ3nLtuQGSUN0SBsmAgFQwWMdFIOg8dO09bQ7QgB09GwmdcJgOCvR9Jg-QDIYlxGEZkhSAARFIck2DAWBUDY3kwul1ggEJUBfA4jjgTR5nWeA+0IQQIAhEh5ApJCEkYr49W7IF+TlSlWVQNZJH2ETjCEPlw3mOBUAADzkMB4G+alTDAz5FO4IA

**Comment by paambaati** [comment]
@jgoux Please feel free to reopen this issue if you'd like to ask more questions.
